import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nevadapath</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Nevadapath - Grade distributions data for UNR</title>

        <meta name="title" content="UNR Course Grade Distributions" />
        <meta
          name="description"
          content="Get statistics and grade distributions for University of Nevada, Reno courses. Find out how your course compares to others."
        />
        <meta name="robots" content="index, follow" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="English" />

        <meta property="og:title" content="Nevadapath - UNR Course Data" />
        <meta property="og:site_name" content="Nevadapath" />
        <meta property="og:url" content="https://www.nevadapath.com" />
        <meta
          property="og:description"
          content="Get statistics and grade distributions for University of Nevada, Reno courses. Find out how your course compares to others."
        />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content="https://www.nevadapath.com/images/nevadapath.jpg"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@nevadapath" />
        <meta name="twitter:creator" content="@nevadapath" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-white"></section>
      </main>
    </>
  );
};

export default Home;
